## What is numpy?
  1. **Numerical python** in short **numpy** is a python library which is used mainly for working with **n dimensional arrays**. It consists of all the required mathematical functions.
  2. Unlike lists numpy arrays are faster as it uses well optimized **C compiled code**.
  3. It also has functions for working in domain of **linear algebra**, **fourier transform**, and **matrices**.
  4. Numpy code base "https://github.com/numpy/numpy"

  ***Note***: NumPy was created in 2005 by Travis Olliphant.

## Why numpy is widely used in ML?
  1. Numpy n dimensional arrays are faster, effcient in mathematical and scientific operations.
  2. Sophisticated (broadcasting) functions.
  3. Tools for integrating C/C++ and Fortran code.
  4. Useful linear algebra, Fourier transform, and random number capabilities.

## Why numpy is faster?
  Two reasons
  1. It uses well optimized C-compiled code at the backend
  2. General reason is, the array elements are stored in contiguos memory locations(locality of reference) unlike lists.
  3. Array requires only one look up into the memory to get the required data where as lists requires two look ups in the memory.

***Note***: Besides its obvious scientific uses, NumPy in Python can also be used as an efficient multi-dimensional container of generic data. Arbitrary data types can be defined using Numpy which allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

***Note***: numpy library "https://docs.scipy.org/doc/numpy-1.10.1/reference/index.html"

Source: geeksforgeeks

### CREATION OF NUMPY ARRAYS

In [1]:
#creation of numpy arrays
import numpy as np
nparray1 = np.array([[1,2,3],
                     [4,5,6]], dtype=float)

# type of numpy array
print("numpy array type is: ",type(nparray1))

# rank or dimensions of numpy array
print("Rank or number of dimensions of array",nparray1.ndim)

# Shape of numpy array
print("Shape of the numpy array: ", nparray1.shape)

# size of the numpy array
print("Size of the numpy array: ", nparray1.size)

# datatype of elements of numpy array
print("Datatype of the elements of numpy array: ",nparray1.dtype)

numpy array type is:  <class 'numpy.ndarray'>
Rank or number of dimensions of array 2
Shape of the numpy array:  (2, 3)
Size of the numpy array:  6
Datatype of the elements of numpy array:  float64


***Note***: You can also use np.ndim(nparray1) in place of nparray1.ndim

## ARRAY INDEXING

#### Working with 2 dimensional arrays

In [2]:
# if we dont specify dtype in the array creation, then default will be integer datatype
# creation of numpy arrays from tuples
nparray2 = np.array(((1,2,3),
                     (4,5,6),
                     (7,8,9)), dtype=int)

# print 2nd row 3rd element
print("Element at 2nd row and 3rd column is: ",nparray2[1,2])

# print 1st column
print("1st column of array is: ",nparray2[:, 0])

# print 3rd row
print("3rd row of array is: ",nparray2[2, :])

# print last 2 rows of the array
print("The last 2 rows of the array are: ", nparray2[1::, :])

# print last 2 rows in which each row elements is in reverse order
print("Last 2 rows each row elements is reversed: ", nparray2[1::, -1::-1])

# print the entire array in reverse order
print("Array reverse order: ", nparray2[-1::-1, -1::-1])

Element at 2nd row and 3rd column is:  6
1st column of array is:  [1 4 7]
3rd row of array is:  [7 8 9]
The last 2 rows of the array are:  [[4 5 6]
 [7 8 9]]
Last 2 rows each row elements is reversed:  [[6 5 4]
 [9 8 7]]
Array reverse order:  [[9 8 7]
 [6 5 4]
 [3 2 1]]


#### Working with 3 dimensional arrays

In [3]:
# if we dont specify dtype in the array creation, then default will be integer datatype
nparray3 = np.array((((1,2,3),(4,5,6),(7,8,9)),
                     ((10,11,12),(13,14,15),(16,17,18))))

# dimensions of the array
print("Dimension of the array: ", np.ndim(nparray3))

# Shape of the array
print("Shape of the array: ", np.shape(nparray3))

Dimension of the array:  3
Shape of the array:  (2, 3, 3)


In [4]:
# print 1st 2 dimensional array element
print("1st 2 dimensional array element: ", nparray3[0, :, :]) # nparray3[1] also yields same results

# print 2nd 2 dimensional array in reverse order
print("2nd 2 dimensional array reverse order: ", nparray3[1, -1::-1, -1::-1])

# print last 2 rows of each 2 dimensional arrays
print("last 2 rows of each 2 dimensional arrays: ", nparray3[:, 1::, :])

# print last 2 rows of each 2 dimensional arrays in reverse order
print("last 2 rows of each 2 dimensional arrays in reverse order: ", nparray3[:, 1::, -1::-1])

1st 2 dimensional array element:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
2nd 2 dimensional array reverse order:  [[18 17 16]
 [15 14 13]
 [12 11 10]]
last 2 rows of each 2 dimensional arrays:  [[[ 4  5  6]
  [ 7  8  9]]

 [[13 14 15]
  [16 17 18]]]
last 2 rows of each 2 dimensional arrays in reverse order:  [[[ 6  5  4]
  [ 9  8  7]]

 [[15 14 13]
  [18 17 16]]]


## ARRAYS WITH INTIAL PLACEHOLDERS

In [5]:
# creation of array with zeros as intial placeholder
npzeors = np.zeros((2,3), dtype=complex)
print("numpy array with zeros: ",npzeors)

# creation of array with identity matrix
npeye = np.eye(3)
print("numpy identity matrix: ",npeye)

# print 6 linearly spaced elements between 0 to 1
nplinspace = np.linspace(0,1,6)
print("6 linearly spaced elements between 0 to 1: ", nplinspace)

# creation of arrays with intial placeholder as 1
npones = np.ones((3,3))
print("numpy array with ones: ", npones)

numpy array with zeros:  [[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]
numpy identity matrix:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
6 linearly spaced elements between 0 to 1:  [0.  0.2 0.4 0.6 0.8 1. ]
numpy array with ones:  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### Other useful **functions**

In [6]:
# numpy arange function
print("numpy arange function from 0 to 10 with spaces of 2 in between: ",np.arange(0,10,2))
print("numpy arange function from 0 to 10 with spaces of 2 in between and applying reshaping after it: ",np.arange(0, 10, 3).reshape((2,2)))
print("random.randint(10,100,10): ",np.random.randint(10, 100, 10))
print("6 random elements between 0 and 1: ",np.random.random(6))
print("3 random elements from the list of [1,2,3,....,9]: ",np.random.choice([1,2,3,4,5,6,7,8,9], 3))

numpy arange function from 0 to 10 with spaces of 2 in between:  [0 2 4 6 8]
numpy arange function from 0 to 10 with spaces of 2 in between and applying reshaping after it:  [[0 3]
 [6 9]]
random.randint(10,100,10):  [42 18 97 61 48 44 67 23 12 51]
6 random elements between 0 and 1:  [0.21908156 0.50759421 0.25403415 0.73918604 0.75808059 0.18249116]
3 random elements from the list of [1,2,3,....,9]:  [5 6 2]


Note: For other useful functions go to "https://colab.research.google.com/corgiredirector?site=https%3A%2F%2Fdocs.scipy.org%2Fdoc%2Fnumpy-1.10.1%2Freference%2Findex.html%22"

## ARRAY OPERATIONS

In [7]:
nparray4 = np.array(((1,2,3),
                     (4,5,6),
                     (7,8,9)), dtype=float)

# adding 1 to each element
print(nparray4 + 1)

# multiply each element with 10
print(nparray4 * 10)

# Cumulative sum of each row
print(np.cumsum(nparray4, axis=1))

# Sum of all elements
print(np.sum(nparray4))

# Sum of each row
print(np.sum(nparray4, axis=1))

# max element of each column
print(np.max(nparray4,axis=0))

[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
[[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]]
[[ 1.  3.  6.]
 [ 4.  9. 15.]
 [ 7. 15. 24.]]
45.0
[ 6. 15. 24.]
[7. 8. 9.]


#### Other important operations

In [8]:
# Other important operations
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# add arrays
print ("Array sum:\n", a + b)

# multiply arrays (elementwise multiplication)
print ("Array multiplication:\n", a*b)

# matrix multiplication
print ("Matrix multiplication:\n", a.dot(b))


Array sum:
 [[ 6  8]
 [10 12]]
Array multiplication:
 [[ 5 12]
 [21 32]]
Matrix multiplication:
 [[19 22]
 [43 50]]


## NUMPY UNIVERSAL FUNCTIONS(UFUNCS)

In [9]:
print("exp(a): ",np.exp(a))
print("sine(a): ",np.sin(a))
print("log(a): ",np.log(a))

exp(a):  [[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
sine(a):  [[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]
log(a):  [[0.         0.69314718]
 [1.09861229 1.38629436]]


***Note***: Refer "https://docs.scipy.org/doc/numpy-1.10.1/reference/ufuncs.html#ufunc" for other ufuncs

## ARRAYS SORTING

In [10]:
# source: geeks for geeks
sort_a = np.array([[1, 4, 2],
				           [3, 4, 6],
			             [0, -1, 5]])

# sorted array
print ("Array elements in sorted order:\n",
					np.sort(sort_a, axis = None))

# sort array row-wise
print ("Row-wise sorted array:\n",
				np.sort(sort_a, axis = 1))

# specify sort algorithm
print ("Column wise sort by applying merge-sort:\n",
			np.sort(sort_a, axis = 0, kind = 'mergesort'))

# Example to show sorting of structured array
# set alias names for dtypes
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]

# Values to be put in array
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7),
		('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]

# Creating array
sort_a1 = np.array(values, dtype = dtypes)
print ("\nArray sorted by names:\n",
			np.sort(sort_a1, order = 'name'))

print ("Array sorted by graduation year and then cgpa:\n",
				np.sort(sort_a1, order = ['grad_year', 'cgpa']))


Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]
Row-wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
Column wise sort by applying merge-sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]

Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Array sorted by graduation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]
